Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "Седых Иван"
COLLABORATORS = ""

---

In [2]:
import numpy as np
from numpy.testing import assert_allclose

# 1. Степенная итерация

Дана квадратная $n \times n$ матрица $A$. Алгоритм степенной итерации позволяет найти максимальное собственное значение $\lambda$ матрицы $A$. Для начала необходимо задать начальное приближение собственного вектора $x_0$. 


Модифицированный алгоритм степенной итерации:

1. $y_{k+1} = A x_k$

2. $x_{k+1} = \cfrac{y_{k+1}}{||y_{k+1}||}$

3. $\lambda^{(k)} = (x_k, y_{k+1})$

где $k$ - номер итерации.

Напишите функцию, реализующую поиск максимального собственного значения заданной матрицы с помощью алгоритма степенной итерации.

In [3]:
def power_iter(a, vec, eps=1e-3, maxiter=1000):
    """Реализует алгоритм степенной итерации поиска максимального собственного значения матрицы `a` 
        с начальным приближением собственного вектора vec.
    
    Parameters
    ----------
    a : array-like of floats, shape (n, n)
        Введённая матрица
    vec : array-like of floats, shape (n,)
        Введённое начальное приближение собственного вектора
    eps : float
        Введённая абсолютная точность
    maxiter : integer
        Максимальное количество итераций
    
    Returns
    -------
    lm : float
        Приближение максимального собственного значения
    outvec : array of floats, shape (n,)
        Приближение собственного вектора
    iters : integer
        Количество итераций
    """
    a = np.asarray(a, dtype=float)
    if a.ndim != 2:
        raise ValueError("a.ndim = %s, expected 2" % a.ndim)
    
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
        
    if (a.shape[0] != a.shape[1]):
        raise ValueError("a is not square")
        
    if (a.shape[0] != vec.shape[0]):
        raise ValueError("vec should be of length %s" % a.shape[0])
    
    for i in range(maxiter):
        y = a @ vec
        new_vec = y / np.linalg.norm(y)
        lm = new_vec @ y

        err = np.linalg.norm(y - lm * vec) / np.linalg.norm(vec)
        if err < eps:
            break
        
        vec = new_vec
    return lm, vec, i

Протестируйте свою функцию на следующих примерах:

In [4]:
A = np.asarray([[4, 34],[7, 1]])

np.random.seed(123)
x = np.random.random(size=2)

l, e, k = power_iter(A, x)
assert_allclose(A @ e, l * e, atol=1e-3)

l, e, k = power_iter(A, x, 1e-5)
assert_allclose(A @ e, l * e, atol=1e-5)


# 2. Обратная итерация

Этот метод может использоваться, например, для поиска собственных векторов матрицы, если уже имеется достаточно хорошее приближение её максимального собственного значения.

Для реализации алгоритма необходимо задать начальные приближения для собственного вектора $x_0$ и собственного значения $\mu$.

На каждой итерации метода решается система уравнений:
$$(A - \lambda^{(k)} I) y_{k+1} = x_k,$$
приэтом $\lambda^{(0)} = \mu$. После этого за новое приближение собственного вектора принимается нормированный вектор $y_{k+1}$:
$$x_{k+1} = \cfrac{y_{k+1}}{||y_{k+1}||}.$$

In [17]:
def inverse_iter(a, vec, mu, eps=1e-3, maxiter=1000):
    """Реализует алгоритм степенной итерации поиска максимального собственного значения матрицы a 
        с начальным приближением собственного вектора vec и начальным приближением собственного значения mu
    
    Parameters
    ----------
    a : array-like of floats, shape (n, n)
        Введённая матрица
    vec : array-like of floats, shape (n,)
        Введённое начальное приближение собственного вектора
    mu : float
        Введённое начальное приближение собственного значения
    eps : float
        Введённая точность 
    maxiter : integer
        Максимальное количество итераций
    
    Returns
    -------
    lm : float
        Приближение максимального собственного значения
    outvec : array of floats, shape (n,)
        Приближение собственного вектора
    iters : integer
        Количество итераций
    """
    a = np.asarray(a, dtype=float)
    if a.ndim != 2:
        raise ValueError("a.ndim = %s, expected 2" % a.ndim)
    
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
        
    if (a.shape[0] != a.shape[1]):
        raise ValueError("a is not square")
        
    if (a.shape[0] != vec.shape[0]):
        raise ValueError("vec should be of length %s" % a.shape[0])

    lm = mu
    for i in range(maxiter):
        lm = vec @ a @ vec
        B = a - lm * np.eye(a.shape[0])
        if np.linalg.det(B) == 0:
            break
        y = np.linalg.solve(B, vec)
        new_vec = y / np.linalg.norm(y)

        err = np.linalg.norm(y - lm * vec) / np.linalg.norm(vec)
        # print(err, eps)
        if err < eps:
            break
        
        vec = new_vec
    return lm, vec, i

Протестируйте свою функцию на следующих примерах:

In [18]:
A = np.asarray([[4, 34],
                [7, 1]])
x = np.random.random(size=2)

l, e, k = inverse_iter(A, x, 1.)
assert_allclose(A @ e, l * e, atol=1e-3)

l, e, k = inverse_iter(A, x, 100.)
assert_allclose(A @ e, l * e, atol=1e-3)


## Пример

Рассмотрите матрицу 
$$ A = 
\begin{bmatrix}
3 & 1 & 0 & 0\\ 
1 & 2 & 0 & 1\\ 
0 & 0 & 1 & 1\\ 
0 & 1 & 1 & 1
\end{bmatrix}.
$$

In [7]:
# Определите матрицу `А` и задайте начальное приближение для собственного вектора
# (используйте случайный начальный вектор)

def A_and_x(seed=1234):
    """Возвращает матрицу `А` и случайный начальный вектор."""

    A = np.array([
        [3,1,0,0],
        [1,2,0,1],
        [0,0,1,1],
        [0,1,1,1]
    ])
    x = np.random.normal(size=A.shape[0])
    return A, x

Найдите максимальное собственное число этой матрицы тремя разными методами.

### 1) Степенная итерация

In [8]:
A, x = A_and_x()

l, e, k = power_iter(A, x)
assert_allclose(A @ e, l * e, atol=1.6e-2)


### 2) Обратная итерация с $\mu = 3.5$

In [9]:
A, x = A_and_x()

l, e, k = inverse_iter(A, x, 3.5)
assert_allclose(A @ e, l * e, atol=1e-3)


### 3) Обратная итерация с $\mu = 3.7$

In [10]:
A, x = A_and_x()

l, e, k = inverse_iter(A, x, 3.7)
assert_allclose(A @ e, l * e, atol=1e-3)


Сколько шагов $k$ требуется в каждом случае для того, чтобы получить настоящий собственный вектор $x^*$ с точностью $||x^* - x_k||_2 < 10^{-3}$?

In [11]:
A, x = A_and_x()

l, e, k = power_iter(A, x, eps=1e-3)
assert_allclose(A @ e, l * e, atol=1.6e-2)
print(f"1: k={k}")

l, e, k = inverse_iter(A, x, 3.5, eps=1e-3)
assert_allclose(A @ e, l * e, atol=1e-3)
print(f"2: k={k}")

l, e, k = inverse_iter(A, x, 3.7, eps=1e-3)
assert_allclose(A @ e, l * e, atol=1e-3)
print(f"3: k={k}")

1: k=11
2: k=999
3: k=999


In [14]:
l,e

(3.7508004220609164,
 array([-0.77250966, -0.58000058, -0.08832178, -0.2429556 ]))

In [12]:
np.linalg.eig(A)

(array([ 3.75080042, -0.28399787,  1.21473855,  2.3184589 ]),
 array([[-0.77250966,  0.11203111, -0.35688275,  0.51313991],
        [-0.58000058, -0.36790993,  0.63712901, -0.34972594],
        [-0.08832178, -0.56719284, -0.66792899, -0.4736691 ],
        [-0.2429556 ,  0.7282744 , -0.1434301 , -0.62451324]]))